### ISSUE TITLE
Make the text wider on the essay sections

### ISSUE THREAD

**Issue by juliastone0729** [thecdil/wolf-reintroduction#8]
@evanwill would this involve editing the tufte.scss file?

**Comment by evanwill** [comment]
Let me think about that one. The way tufte does it is a little complicated. We might not be using much of tufte at all any more, so might just swap out all together. 
The narrow text body is for readability (not just to create space), you don't want the text block to get too big because longer lines are harder to read. It sounds like she would like it sort of like the About page, narrow but centered?

**Comment by juliastone0729** [comment]
@evanwill Just touched base with Flori on this and she is interested in having the essay sections more like the About page, narrow but centered

**Comment by evanwill** [comment]
updated, just using the About style layout and includes
